name: Deploy Service and Evaluate Mongo

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env: 
      DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Deploy
      run: |
          curl -X POST "$DEPLOY_HOOK_URL"
