name: Deploy Service and Evaluate Mongo

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Deploy
      run: |
          curl -X POST https://api.render.com/deploy/srv-cvlfmrggjchc73bmtsf0?key=n0jnrV7O2wU
