name: Deploy Service and Evaluate Mongo

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Deploy
      run: |
          curl -X POST https://api.render.com/deploy/srv-cvkhpahr0fns739rtghg?key=fx_zMRhRBs4
