name: Deploy Service and Evaluate Mongo

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest  

    env:
       Solution_Name: Projects\Exadel.ReportHub\Exadel.ReportHub.sln
       Test_Project: Projects\Exadel.ReportHub\Exadel.ReportHub.Tests\Exadel.ReportHub.Tests.csproj 
       
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --no-restore
      
    - name: Publish
      run: dotnet publish ${{ env.Solution_Name }} --no-build

    - name: Build the docker image
      run: docker build . -f Dockerfile -t {Here'll be dockerHubName}:latest

    - name: Push image to {somewhere}
      run: docker login -u {login} -p ${{secrets.DOCKER_HUB_TOKEN}}
           docker push {Here'll be dockerHubName}
           
    - name: Run Mongo Scripts
    
    
