name: Deploy Service and Evaluate Mongo

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env: 
      deploy_url: ${{ secrets.DEPLOY_HOOK }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Deploy
      run: |
          curl "$deploy_url"
