name: Deploy Service and Evaluate Mongo

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Chechout
      - uses: actions/checkout@v3
      
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.DEPLOY_HOOK }}
        run: |
          curl "$deploy_url"
