name: Deploy Service and Evaluate Mongo

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest  

    env:
       SOLUTION_NAME: Projects\Exadel.ReportHub\Exadel.ReportHub.sln
       RENDER_REPO: report_hub
       DEPLOY_HOOK: "https://api.render.com/deploy/srv-cvkhpahr0fns739rtghg?key=fx_zMRhRBs4"
       DOCKERFILE_PATH: Projects/Exadel.ReportHub/Dockerfile
       IMAGE_NAME: report-hub
       RENDER_USERNAME: makar.kniazeu@gmail.com
       RENDER_TOKEN: rnd_pHpyr5tHU9iajHDrOCsZCIHlOZrO
       
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Hook
        run: curl -X POST "https://api.render.com/deploy/srv-cvkhpahr0fns739rtghg?key=fx_zMRhRBs4"
